# Copyright (c) AIoWay Authors - All Rights Reserved

"The high level operators that are just torch functions / data."

import abc
import typing
from collections import abc as cabc

import torch

from aioway._fn import thunk_dcls

from .hop import Hop, thunk_dcls

__all__ = ["TensorHop", "CatHop", "StackHop"]


@thunk_dcls
class TensorHop[T = object](Hop):
    """
    The `Hop` for `torch.Tensor`s (generated by `torch.randn` / `torch.tensor` etc),
    or e.g. `td.TensorDict`, or any object that contains `torch.Tensor`s.
    """

    data: T
    "Backing data."

    @typing.override
    def forward(self) -> T:
        return self.data


@thunk_dcls
class _CatStackHop(Hop, abc.ABC):
    """
    The `Hop` implementation for `torch.cat` / `torch.stack`.
    """

    FUNCTION: typing.ClassVar[cabc.Callable[..., torch.Tensor]]
    """
    Either `torch.cat` or `torch.stack` or something like those.
    It's typed as `cabc.Callable[..., torch.Tensor]`
    because `torch` has complicated type stubs, annoying to deal with.
    """

    tensors: list[Hop]
    "The list of `Hop` that would evaluate each to a `torch.Tensor`."

    dim: int = 0
    "The `dim` flag that would be passed to `.function`."

    def forward(self) -> torch.Tensor:
        return self.FUNCTION(self.tensors, dim=self.dim)


class CatHop(_CatStackHop):
    "The `Hop` backed by `torch.cat`."

    FUNCTION = torch.cat


class StackHop(_CatStackHop):
    "The `Hop` backed by `torch.stack`."

    FUNCTION = torch.stack
