# Copyright (c) AIoWay Authors - All Rights Reserved

"The [h]igh level [o]peration [p]review class."

import abc
import contextlib as ctxl
import dataclasses as dcls
import typing
from collections import abc as cabc

from aioway._utils import AnyDict, DagNode, dcls_asdict, decomp_flatten, topo_sort

__all__ = ["Hop", "HopDag", "hop_cache_on", "hop_cache"]

_hop_cache: AnyDict[Hop] | None = None
"The cache instance for `Hop`."


@typing.dataclass_transform()
def hop_dcls(cls: type):
    return dcls.dataclass(match_args=False)(cls)


@hop_dcls
class Hop(abc.ABC):
    """
    `Hop` is the node that would be evaluated during run time.
    It will output `torch.Tensor` a container that makes up of them.
    """

    def __hash__(self) -> int:
        return id(self)

    @typing.final
    def __call__(self) -> object:
        if _hop_cache is None:
            return self.forward()

        # Do the caching if enabled.

        cache = hop_cache()

        if self not in cache:
            cache[self] = self.forward()

        return cache[self]

    @abc.abstractmethod
    def forward(self) -> object:
        """
        The forwarding logic. Should invoke dependencies' `__call__` methods.
        """

        raise NotImplementedError

    @property
    @abc.abstractmethod
    def requires_grad(self) -> bool:
        """
        Whether or not the `torch.Tensor`s generated by this `Hop` `requires_grad`.
        If `False`, much like `torch`'s `requires_grad`,
        gradient does not need to propagate to this node, and we can do a graph break.
        """

        raise NotImplementedError

    def rebuild(self):
        """
        Rebuild the current `Hop`. This is useful when you are switching contexts,
        e.g. switching on real mode after configuring the `HopDag` in fake mode.
        """

        copied = self._rebuild()
        assert copied is not self
        return copied

    @abc.abstractmethod
    def _rebuild(self) -> typing.Self:
        raise NotImplementedError


@ctxl.contextmanager
def hop_cache_on():
    """
    Turn on caching for `Hop`. Everytime you call `hop_cache_on`,
    a new scope is created and so a new cache is created.
    (The old cache still stays in memory so it'll still be "active").
    """

    global _hop_cache

    _hop_cache = AnyDict[Hop](Hop)
    try:
        yield _hop_cache
    finally:
        _hop_cache = None


def hop_cache() -> AnyDict[Hop]:
    """
    The active cache for `Hop`. If there is no active session, raise `RuntimeError`.
    """

    if _hop_cache is None:
        raise RuntimeError("`hop_cache` can only be called in `hop_cache_on` scope.")

    return _hop_cache


@dcls.dataclass
class HopNode:
    """
    `HopNode` is a node in DAG.
    Since it stores indices, it only makes sense used by a `HopDag`.
    """

    dag: list[Hop]
    "The dag of the node."

    idx: int
    "The operator represented by this node is stored in this index.."

    in_idxs: set[int] = dcls.field(default_factory=set)
    "The input indices."

    out_idxs: set[int] = dcls.field(default_factory=set)
    "The output indices."

    def __post_init__(self) -> None:
        if not 0 <= self.idx < (length := len(self.dag)):
            raise IndexError(f"The dag has size {length}, but {self.idx=}.")

        if not all(0 <= ipt < self.idx for ipt in self.in_idxs):
            raise IndexError(
                f"Input index {self.in_idxs=} contains indices >= {self.idx=}."
            )

        if not all(self.idx < opt < length for opt in self.out_idxs):
            raise IndexError(
                f"Input index {self.out_idxs=} contains indices <= {self.idx=}."
            )

    @property
    def hop(self) -> Hop:
        return self.dag[self.idx]

    @property
    def num_inputs(self):
        return len(self.in_idxs)

    @property
    def num_outputs(self):
        return len(self.out_idxs)

    def add_input(self, idx: int):
        if idx >= self.idx:
            raise IndexError(f"Input index {idx=} >= {self.idx=}.")

        self.in_idxs.add(idx)

    def add_output(self, idx: int):
        if idx <= self.idx:
            raise IndexError(f"Output index {idx=} <= {self.idx=}.")

        self.out_idxs.add(idx)

    def inputs(self) -> cabc.Generator[Hop]:
        "Get the input hops."

        for input in self.in_idxs:
            yield self.dag[input]

    def outputs(self) -> cabc.Generator[Hop]:
        "Get the output hops."
        for output in self.out_idxs:
            yield self.dag[output]

    @property
    def is_input(self) -> bool:
        return not self.in_idxs

    @property
    def is_output(self) -> bool:
        return not self.out_idxs


@dcls.dataclass
class HopDag:
    """
    The DAG of `HopInit`s or `HopFwd`s.
    """

    nodes: list[HopNode]
    "The ordered nodes."

    def __len__(self):
        return len(self.nodes)

    def __getitem__(self, idx: int) -> Hop:
        return self.nodes[idx].hop

    def __iter__(self) -> cabc.Generator[Hop]:
        for idx in range(len(self)):
            yield self[idx]

    def __call__(self) -> list[object]:
        "Evaluating the `HopInit`/`HopFwd`."

        return [node.hop() for node in self.nodes]

    @property
    def input_nodes(self) -> list[Hop]:
        "Get the input nodes."

        return [node.hop for node in self.nodes if node.is_input]

    @property
    def output_nodes(self) -> list[Hop]:
        "Get the output nodes."

        return [node.hop for node in self.nodes if node.is_output]

    @classmethod
    def from_list_of_nodes(cls, nodes: list[Hop]) -> typing.Self:
        ordered_hop = topo_sort([_to_dag_node(node) for node in nodes])

        hop_nodes: list[HopNode] = []
        hop_id_to_dag_idx = {id(hop): idx for idx, hop in enumerate(ordered_hop)}

        for idx, hop in enumerate(ordered_hop):
            node = HopNode(ordered_hop, idx)

            deps_idxs = [
                hop_id_to_dag_idx[id(dep)]
                for dep in decomp_flatten(dcls_asdict(hop), Hop)
            ]

            # Link them together.
            for dep_idx in deps_idxs:
                node.add_input(dep_idx)
                hop_nodes[dep_idx].add_output(idx)

            hop_nodes.append(node)

        return cls(hop_nodes)


def _to_dag_node(hop: Hop) -> DagNode[Hop]:
    """
    The dependent `Hop`s. It's decomposed from the dataclass members.
    """

    # Flatten the dict version s.t. we do not include `self`.
    deps: list[Hop] = list(decomp_flatten(dcls_asdict(hop), Hop))
    return DagNode(key=hop, deps=deps)
