# Copyright (c) AIoWay Authors - All Rights Reserved

"The [h]igh level [o]peration [p]review class."

import abc
import contextlib as ctxl
import copy
import dataclasses as dcls
import typing
from collections import abc as cabc

from aioway._utils import (
    AnyDict,
    AnySet,
    DagNode,
    dcls_asdict,
    decomp_dcls_members,
    topo_sort,
)

__all__ = ["Hop", "HopList", "HopDict", "hop_dcls", "hop_cache_on", "hop_cache"]

_hop_cache: AnyDict[Hop] | None = None
"The cache instance for `Hop`."


@ctxl.contextmanager
def hop_cache_on() -> cabc.Generator[AnyDict[Hop]]:
    """
    Turn on caching for `Hop`. Everytime you call `hop_cache_on`,
    a new scope is created and so a new cache is created.
    (The old cache still stays in memory so it'll still be "active").

    Returns:
        A context manager that when activates, intercept all `Hop.__call__` calls,
        and stores the outputs s.t. second `.__call__()` uses the previous rersult.
    """

    global _hop_cache
    before, _hop_cache = _hop_cache, AnyDict[Hop](Hop)

    try:
        yield _hop_cache
    finally:
        _hop_cache = before


def hop_cache() -> AnyDict[Hop]:
    """
    The active cache for `Hop`. If there is no active session, raise `RuntimeError`.
    """

    if _hop_cache is None:
        raise RuntimeError("`hop_cache` can only be called in `hop_cache_on` scope.")

    return _hop_cache


@typing.dataclass_transform()
def hop_dcls(cls: type):
    return dcls.dataclass(match_args=False)(cls)


@hop_dcls
class Hop(abc.ABC):
    """
    `Hop` is the node that would be evaluated during run time.
    It will output `torch.Tensor` a container that makes up of them.
    """

    def __hash__(self) -> int:
        return id(self)

    @typing.final
    def __call__(self) -> object:
        if _hop_cache is None:
            return self.forward()

        # Do the caching if enabled.
        elif self not in _hop_cache:
            _hop_cache[self] = self.forward()

        return _hop_cache[self]

    @abc.abstractmethod
    def forward(self) -> object:
        """
        The forwarding logic. Should invoke dependencies' `__call__` methods.
        """

        raise NotImplementedError

    @property
    def requires_grad(self) -> bool:
        """
        Whether or not the `torch.Tensor`s generated by this `Hop` `requires_grad`.
        If `False`, much like `torch`'s `requires_grad`,
        gradient does not need to propagate to this node, and we can do a graph break.

        Defaults to `False` if not overwritten.
        """

        return False

    def replace(self, function: cabc.Callable[[Hop], Hop | None]) -> Hop:
        """
        Replace the current `node` with `function(node)` if it's not `None`,
        or else recursively invoke `.replace(function)` on `Hop` in `.inputs()`.
        """

        if mapped := function(self):
            return mapped

        sub_dict = {
            name: hop.replace(function)
            for name, hop in dcls_asdict(self).items()
            if isinstance(hop, Hop)
        }
        return dcls.replace(self, **sub_dict)

    def rebuild(self):
        """
        Rebuild the current `Hop`. This is useful when you are switching contexts,
        e.g. switching on real mode after configuring the `HopDag` in fake mode.

        If `self._rebuild()` is not overwritten, defaults to shallow copying `self`.
        """

        copied = self._rebuild()
        assert copied is not self
        return copied

    def _rebuild(self) -> typing.Self:
        return copy.copy(self)

    def deps(self) -> cabc.Iterator[Hop]:
        "Decompose `self`, get the immediate dependencies."

        for hop in decomp_dcls_members(self, Hop):
            yield hop

    def nodes(self) -> AnySet[Hop]:
        "Get all the nodes recursively, including `self`."

        nodes = AnySet[Hop](Hop)

        # Add nodes recursively.
        def _visit_nodes(hop: Hop):
            if hop in nodes:
                return

            nodes.add(hop)

            for dep in hop.deps():
                _visit_nodes(dep)

        _visit_nodes(self)
        return nodes

    @property
    def is_source(self) -> bool:
        "If the `Hop` is not dependent on other `Hop`s, it's considered a source."

        for _ in decomp_dcls_members(self, Hop):
            return True
        else:
            return False


class HopTensorList:
    """
    An output list, using a pull strategy to pull in the data when called.
    """


@hop_dcls
class HopList(Hop, cabc.Sequence[Hop]):
    "A convenient list of `Hop`s."

    hops: list[Hop]
    """
    The hop list that this `HopList` represents.
    """

    def __repr__(self) -> str:
        return repr(self.hops)

    def __len__(self) -> int:
        return len(self.hops)

    @typing.overload
    def __getitem__(self, key: int) -> Hop: ...

    @typing.overload
    def __getitem__(self, key: slice) -> typing.Self: ...

    def __getitem__(self, key):
        if isinstance(key, int):
            return self.hops[key]

        if isinstance(key, slice):
            return type(self)(self.hops[key])

        raise TypeError(f"Don't know how to handle {type(key)=}.")

    def __iter__(self) -> cabc.Iterator[Hop]:
        yield from self.hops

    @typing.override
    def forward(self) -> list[typing.Any]:
        return [hop() for hop in self.hops]

    def dag(self) -> list[Hop]:
        "Order the `Hop`s in their topological order."

        dag_nodes = [DagNode(key=hop, deps=list(hop.deps())) for hop in self.nodes()]
        return topo_sort(dag_nodes)


@hop_dcls
class HopDict(Hop, cabc.Mapping[str, Hop]):
    "A convenient dict of `Hop` (usually a dict)."

    hops: dict[str, Hop]
    """
    The hop dict that this `HopDict` represents.
    """

    def __repr__(self) -> str:
        return repr(self.hops)

    def __len__(self) -> int:
        return len(self.hops)

    def __getitem__(self, key: str) -> Hop:
        return self.hops[key]

    def __contains__(self, key: object) -> bool:
        return key in self.hops

    def __iter__(self) -> cabc.Generator[str]:
        yield from self.hops

    @typing.override
    def keys(self) -> cabc.KeysView[str]:
        return self.hops.keys()

    @typing.override
    def forward(self) -> dict[str, typing.Any]:
        return {key: hop() for key, hop in self.hops.items()}

    def to_hop_list(self) -> HopList:
        "Convert to `HopList` (for their utilities like `.dag()`)."

        return HopList(list(self.values()))
