# Copyright (c) AIoWay Authors - All Rights Reserved

"The index (currently only faiss)."

import abc
import dataclasses as dcls
from collections import abc as cabc

import numpy as np
import torch

from aioway._utils import FloatArray, IntArray

from ._iters import Iter, TensorIter, node_dcls

__all__ = ["AnnIndex", "AnnResult", "AnnIndexIter", "AnnIndexTrainerIter", "FaissIndex"]


@dcls.dataclass(frozen=True)
class AnnResult:
    "Tuple for results generated by `AnnIndex`."

    distance: FloatArray
    """
    The distance for each query and top k pairs. 2D array of (len(query), k).
    """

    indices: IntArray
    """
    The indices for each query and top k pairs. 2D array of (len(query), k).
    """

    def __post_init__(self) -> None:
        if self.distance.ndim != 2:
            raise ValueError(f"Distance is not 2D. {self.distance.shape=}.")

        if self.indices.ndim != 2:
            raise ValueError(f"Indices is not 2D. {self.indices.shape=}.")

        if self.distance.shape[1] != self.indices.shape[1]:
            raise ValueError(
                "`k` mismatch. "
                f"`k` for distance {self.distance.shape[-1]}, "
                f"`k` for indices {self.indices.shape[-1]}."
            )

    @property
    def k(self) -> int:
        "The `k` of the result."

        return self.distance.shape[-1]


class AnnIndex(abc.ABC):
    """
    `AnnIndex` supports faster than `O(n)` look ups for approximate nearest neighbors.
    """

    def __init__(self, dim: int):
        self._dim = dim

    @abc.abstractmethod
    def __len__(self) -> int:
        "The number of samples already trained."

        raise NotImplementedError

    def add(self, x: FloatArray, /) -> None:
        """
        Add a new set of data to the index.
        """

        self._check_input(x)
        self._add_batch(x)

    def search(self, query: FloatArray, k: int = 1) -> AnnResult:
        """
        Perform search on the input.
        """

        self._check_input(query)

        if k <= 0:
            raise ValueError(f"The neighbor count {k} must be positive.")

        result = self._search(query=query, k=k)

        if result.k != k:
            raise AssertionError(f"`k` of output: {result.k}, specified k: {k}.")

        return result

    def _check_input(self, x: FloatArray, /):
        if not isinstance(x, np.ndarray):
            raise TypeError(f"Input should be a numpy array. Got {type(x)=}.")

        if x.ndim != 2:
            raise ValueError(f"Input should be 2D (batch, dim). Got {x.shape=}.")

        if x.shape[-1] != self._dim:
            raise ValueError(
                f"Dimension of index {self._dim} != input dim {x.shape[-1]}."
            )

    @abc.abstractmethod
    def _add_batch(self, x: FloatArray) -> None:
        raise NotImplementedError

    @abc.abstractmethod
    def _search(self, query: FloatArray, k: int = 1) -> AnnResult:
        raise NotImplementedError


class FaissIndex(AnnIndex):
    """
    An index exposing `faiss` API.
    """

    def __init__(self, dim: int, spec: str = "Flat"):
        import faiss

        super().__init__(dim)
        self._idx = faiss.index_factory(dim, spec)

    def __len__(self) -> int:
        return self._idx.ntotal

    def _add_batch(self, x: FloatArray) -> None:
        self._idx.add(x)

    def _search(self, query: FloatArray, k: int = 1) -> AnnResult:
        dist, idx = self._idx.search(query, k)
        return AnnResult(dist, idx)


@node_dcls
class AnnIndexTrainerIter(Iter[None]):
    """
    Train the index for future usage.
    """

    index: AnnIndex
    """
    The index to train.
    """

    data: TensorIter
    """
    The data to index.
    """

    def iterate(self) -> cabc.Generator[None]:
        for batch in self.data:
            self.index.add(batch.cpu().numpy())
            yield


@node_dcls
class AnnIndexIter(TensorIter):
    """
    Iterate and yield the indices.
    """

    index: AnnIndex
    """
    The index to train.
    """

    query: TensorIter
    """
    The querying tensor.
    """

    k: int
    """
    The number of neighbors to return.
    """

    def __post_init__(self) -> None:
        if not len(self.index):
            raise ValueError("The index should have been trained.")

    def iterate(self) -> cabc.Generator[torch.Tensor]:
        for query in self.query:
            result = self.index.search(query.cpu().numpy(), k=self.k)
            yield torch.from_numpy(result.indices)
