name: Pre Commit Checks
on: [push]
jobs:
  format:
    name: 📑 Formatting
    runs-on: ubuntu-latest
    steps:
      - name: 🔔 Check out
        uses: actions/checkout@v3

      - name: 💣 Prepare
        run: pip install nox[pbs] && nox -rs hello

      - name: ⬇️ Python PDM
        uses: pdm-project/setup-pdm@v4
        with:
          cache: true

      - name: 🏃 Formatting
        run: nox -rs format_check

  type:
    name: 👨‍⚕️ Type Checking
    runs-on: ubuntu-latest
    steps:
      - name: 🔔 Check out
        uses: actions/checkout@v3

      - name: 💣 Prepare
        run: pip install nox[pbs] && nox -rs hello

      - name: ⬇️ Python PDM
        uses: pdm-project/setup-pdm@v4
        with:
          cache: true

      - name: 🏃 Type checking
        run: nox -rs type
