name: Unit Testing
on: [push]
jobs:
  unit-test:
    name: 🧪 Unit Testing
    runs-on: ubuntu-latest
    steps:
      - name: 🔔 Check out
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: ⬇️ Python PDM
        uses: pdm-project/setup-pdm@v4

      - name: 💣 Prepare
        run: pip install nox[pbs] && nox -rs setup

      - name: 🧪 Test with pytest
        run: nox -rs test

  build:
    name: 👷 Build
    runs-on: ubuntu-latest
    steps:
      - name: 🔔 Check out
        uses: actions/checkout@v3

      - name: ⬇️ Python PDM
        uses: pdm-project/setup-pdm@v4

      - name: 💣 Prepare
        run: pip install nox[pbs] && nox -rs setup

      - name: 👷‍♂️ Build
        run: nox -rs build
